server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketblitz
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true