server:
  port: 8084

spring:
  application:
    name: payment-service

  # Database Connection (Ensure these match your Docker Compose credentials)
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketblitz
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update # Automatically creates the 'payments' table
    show-sql: true

  # Kafka Connection
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.illusion.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: "com.illusion.*"
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always