server:
  port: 8081

spring:
  application:
    name: booking-service

  # Enable Java 21 Virtual Threads for massive concurrency
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketblitz
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates the 'payments' table
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: "com.illusion.*"
    consumer:
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.illusion.*"
    template:
      default-topic: order-events
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always